### ISSUE TITLE
Uncaught TypeError: Cannot set property 'next' of undefined

### ISSUE THREAD

**Issue by ajbuch2000** [isgj/bang#3]
[Enter steps to reproduce below:]
1. press ctrl-alt-e. 

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.5
**Thrown From**: [bang](https://github.com/isgj/bang) package, v2.0.1
### Stack Trace

Uncaught TypeError: Cannot set property 'next' of undefined

```
At /Users/andrewbuchanan/.atom/packages/bang/lib/bang.coffee:110

TypeError: Cannot set property 'next' of undefined
    at Object.module.exports.Bang.close (/Users/andrewbuchanan/.atom/packages/bang/lib/bang.coffee:110:30)
    at Object.module.exports.Bang.toggle (/Users/andrewbuchanan/.atom/packages/bang/lib/bang.coffee:97:21)
    at atom-text-editor.<anonymous> (/Users/andrewbuchanan/.atom/packages/bang/lib/bang.coffee:44:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -8:27.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  3x -3:08.5.0 bang:edit-text (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.1.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:00.0 bang:edit-text (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "build",
      "minimap",
      "hyperclick",
      "language-perl"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-perl6-editor-tools, v0.9.18 (active)
atomatigit, v1.5.5 (active)
bang, v2.0.1 (active)
build, v0.65.0 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.38 (inactive)
language-diff, v0.4.0 (active)
language-perl6fe, v1.7.3 (active)
linter, v1.11.16 (active)
linter-php, v1.2.0 (active)
minimap, v4.25.0 (inactive)
minimap-highlight-selected, v4.4.0 (active)
monokai-seti, v0.7.0 (inactive)
open-recent, v5.0.0 (active)
refactor, v0.9.2 (active)
todo-show, v1.7.0 (inactive)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by isgj** [comment]
I'm sorry but i am not able to reproduce this issue. I tried it also in a fresh install and it works fine.

**Comment by ajbuch2000** [comment]
Uninstalled and reinstalled and it now works fine, sorry about that. The history feature is nice, thanks!

**Comment by isgj** [comment]
Glad you like it.
